[package]
name = "wayland-experiments"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["unstable", "client"] }
memmap2 = "0.9"
libc = "0.2"
