File.stream!("input.txt")
|> Enum.map(&String.trim/1)
|> Enum.map(&String.split(&1, "   "))
|> Enum.map(fn [a, d] -> {String.to_integer(a), String.to_integer(d)} end)
|> Enum.unzip()
|> (fn {list1, list2} -> [Enum.sort(list1), Enum.sort(list2)] end).()
|> Enum.zip()
|> Enum.map(fn {a, b} -> Kernel.abs(a - b) end)
|> Enum.sum()
|> IO.inspect()
