FROM golang:1.23-alpine3.20
# alpine is not necessary. it can be 1.20 or other tags
# set a working directory to function from. It doesn't have to be /app
WORKDIR /app
# technically you dont need to copy all the files. ONLY the go stuff. But I was being lazy
COPY . .
# this downloads all the dependencies that you have in the code
RUN echo "Listing directory contents:" && ls -la && echo "Done listing directory contents."
RUN go get -v ./...
# or
# RUN go mod download
# create the binary/executable. The name does not have to bin e.g. you can name it mylittlebunny

RUN go build -o main cmd/main.go
# tell docker which binary is your application
ENTRYPOINT [ "/app/main" ]
